import Head from "next/head";
import HomePage from "../components/main/Home";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon/favicon.ico" />
      </Head>
      <HomePage />
    </div>
  );
}
